/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseModal: typeof import('./src/components/modals/BaseModal.vue')['default']
    BestOfThreeModal: typeof import('./src/components/modals/BestOfThreeModal.vue')['default']
    Character: typeof import('./src/components/Character.vue')['default']
    ClashSettings: typeof import('./src/components/modals/ClashSettings.vue')['default']
    CombatReview: typeof import('./src/components/modals/CombatReview.vue')['default']
    CreateAccountModal: typeof import('./src/components/modals/CreateAccountModal.vue')['default']
    DuelHistory: typeof import('./src/components/modals/DuelHistory.vue')['default']
    EquipmentScreen: typeof import('./src/components/modals/EquipmentScreen.vue')['default']
    GamblingModal: typeof import('./src/components/modals/GamblingModal.vue')['default']
    GladiatorMemories: typeof import('./src/components/modals/GladiatorMemories.vue')['default']
    GladiatorStats: typeof import('./src/components/modals/GladiatorStats.vue')['default']
    GladiatorTournamentHistory: typeof import('./src/components/modals/GladiatorTournamentHistory.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InputField: typeof import('./src/components/InputField.vue')['default']
    ItemCard: typeof import('./src/components/ItemCard.vue')['default']
    LoginModal: typeof import('./src/components/modals/LoginModal.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    RoundRobin: typeof import('./src/components/modals/RoundRobin.vue')['default']
    RoundRobinOfThree: typeof import('./src/components/modals/RoundRobinOfThree.vue')['default']
    ScheduleManager: typeof import('./src/components/modals/ScheduleManager.vue')['default']
    SettingsModal: typeof import('./src/components/modals/SettingsModal.vue')['default']
    SideNav: typeof import('./src/components/SideNav.vue')['default']
    SingleElimination: typeof import('./src/components/modals/SingleElimination.vue')['default']
    TextField: typeof import('./src/components/TextField.vue')['default']
  }
}
