services:

  server:
    container_name: server
    restart: always
    build:
      context: /apps/server
      args:
        NODE_PORT: 3001
    ports:
      - 3001:3001

  client:
    build:
      context: /apps/client
    ports:
      - 3000:3000

  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/barry/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped      

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data    

volumes:
  cache:
    driver: local      