services:
  backend:
    build: ./server
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      MONGODB_CONNECTION_STRING: ${MONGO_STRING}
      NODE_ENV: "${ENV}"
      PORT: ${BACKEND_PORT}
      TICK: ${TICK}
      JWT_KEY: "${JWT}"
    networks:
      - app-network

  frontend:
    build: ./client
    ports:
      - "${CLIENT_PORT}:80"
    environment:
      - VITE_BACKEND_STRING=${BACKEND_STRING}
      - VITE_PORT=${BACKEND_PORT}
    depends_on:
      - backend
    networks:
      - app-network


networks:
  app-network:
    driver: bridge  # Use the default bridge network driver