services:
  backend:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      MONGODB_CONNECTION_STRING: mongodb://root:example@192.168.0.15:27017
      NODE_ENV: "prod"
      PORT: 3001
      TICK: 15000
      JWT_KEY: "NEVERFORGET"
    networks:
      - app-network

  frontend:
    build: ./client
    ports:
      - "3005:80"
    depends_on:
      - backend
    networks:
      - app-network


networks:
  app-network:
    driver: bridge  # Use the default bridge network driver