/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseFooter: typeof import('./src/components/modals/BaseFooter.vue')['default']
    BaseModal: typeof import('./src/components/modals/BaseModal.vue')['default']
    BaseTabs: typeof import('./src/components/modals/BaseTabs.vue')['default']
    BaseToolTipModal: typeof import('./src/components/modals/BaseToolTipModal.vue')['default']
    BaseTutorialModal: typeof import('./src/components/modals/BaseTutorialModal.vue')['default']
    BestOfThreeModal: typeof import('./src/components/modals/BestOfThreeModal.vue')['default']
    CardToolTipModal: typeof import('./src/components/modals/CardToolTipModal.vue')['default']
    Char2: typeof import('./src/components/Char2.vue')['default']
    Character: typeof import('./src/components/Character.vue')['default']
    ClashDetail: typeof import('./src/components/modals/DuelReplay/ClashDetail.vue')['default']
    ClashTab: typeof import('./src/components/modals/Tabs/ClashTab.vue')['default']
    CreateAccountModal: typeof import('./src/components/modals/CreateAccountModal.vue')['default']
    DefaultTab: typeof import('./src/components/modals/Tabs/defaultTab.vue')['default']
    DuelHistory: typeof import('./src/components/modals/Tabs/DuelHistory.vue')['default']
    DuelReplay: typeof import('./src/components/modals/DuelReplay.vue')['default']
    DuelSide: typeof import('./src/components/modals/DuelReplay/DuelSide.vue')['default']
    EquipmentTab: typeof import('./src/components/modals/Tabs/EquipmentTab.vue')['default']
    GamblingModal: typeof import('./src/components/modals/GamblingModal.vue')['default']
    GladiatorCard: typeof import('./src/components/GladiatorCard.vue')['default']
    GladiatorDetails: typeof import('./src/components/modals/GladiatorDetails.vue')['default']
    GladiatorHistoryModal: typeof import('./src/components/modals/GladiatorHistoryModal.vue')['default']
    GladiatorOptions: typeof import('./src/components/modals/GladiatorOptions.vue')['default']
    GladiatorStats: typeof import('./src/components/modals/GladiatorStats.vue')['default']
    GladiatorTournamentHistory: typeof import('./src/components/modals/GladiatorTournamentHistory.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InputField: typeof import('./src/components/InputField.vue')['default']
    Item: typeof import('./src/components/modals/Tooltips/item.vue')['default']
    ItemCard: typeof import('./src/components/ItemCard.vue')['default']
    ItemCardDetail: typeof import('./src/components/modals/ItemCardDetail.vue')['default']
    ItemMouseOver: typeof import('./src/components/modals/ItemMouseOver.vue')['default']
    LoginModal: typeof import('./src/components/modals/LoginModal.vue')['default']
    MemoryTab: typeof import('./src/components/modals/Tabs/MemoryTab.vue')['default']
    MouseOver: typeof import('./src/components/MouseOver.vue')['default']
    PointsBar: typeof import('./src/components/modals/DuelReplay/pointsBar.vue')['default']
    PopupBase: typeof import('./src/components/modals/DuelReplay/PopupBase.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    RoundRobin: typeof import('./src/components/modals/RoundRobin.vue')['default']
    RoundRobinOfThree: typeof import('./src/components/modals/RoundRobinOfThree.vue')['default']
    ScheduleManager: typeof import('./src/components/modals/ScheduleManager.vue')['default']
    SettingsModal: typeof import('./src/components/modals/SettingsModal.vue')['default']
    SideNav: typeof import('./src/components/SideNav.vue')['default']
    SingleElimination: typeof import('./src/components/modals/SingleElimination.vue')['default']
    StatsTab: typeof import('./src/components/modals/Tabs/StatsTab.vue')['default']
    TextField: typeof import('./src/components/TextField.vue')['default']
    ToolTipItem: typeof import('./src/components/modals/Tooltips/ToolTipItem.vue')['default']
    TournamentHistory: typeof import('./src/components/modals/Tabs/TournamentHistory.vue')['default']
    WelcomeMain: typeof import('./src/components/WelcomeMain.vue')['default']
  }
}
